# Generated by Django 5.2.7 on 2025-10-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(1, 1), (2, 2)], unique=True)),
                ('is_unlocked', models.BooleanField()),
                ('award_quote', models.CharField(blank=True)),
                ('award_image', models.CharField(blank=True)),
                ('award_link', models.URLField(blank=True, max_length=255)),
            ],
        ),
    ]
