# Generated by Django 5.2.7 on 2025-10-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advent_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='text',
            field=models.CharField(default='Tekst ktory sie tu znajdzie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], unique=True),
        ),
    ]
