# Generated by Django 5.2.7 on 2025-11-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advent_calendar', '0002_day_text_alter_day_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='is_unlocked',
        ),
        migrations.AddField(
            model_name='day',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
