# Generated by Django 5.2.7 on 2025-11-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advent_calendar', '0003_remove_day_is_unlocked_day_open_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='award_image',
            new_name='award_media',
        ),
    ]
